INSERT INTO country(id_country, name) VALUES('AD', 'Andorra');
INSERT INTO country(id_country, name) VALUES('AE', 'United Arab Emirates');
INSERT INTO country(id_country, name) VALUES('AF', 'Afghanistan');
INSERT INTO country(id_country, name) VALUES('AG', 'Antigua & Barbuda');
INSERT INTO country(id_country, name) VALUES('AI', 'Anguilla');
INSERT INTO country(id_country, name) VALUES('AL', 'Albania');
INSERT INTO country(id_country, name) VALUES('AM', 'Armenia');
INSERT INTO country(id_country, name) VALUES('AO', 'Angola');
INSERT INTO country(id_country, name) VALUES('AQ', 'Antarctica');
INSERT INTO country(id_country, name) VALUES('AR', 'Argentina');
INSERT INTO country(id_country, name) VALUES('AS', 'Samoa (American)');
INSERT INTO country(id_country, name) VALUES('AT', 'Austria');
INSERT INTO country(id_country, name) VALUES('AU', 'Australia');
INSERT INTO country(id_country, name) VALUES('AW', 'Aruba');
INSERT INTO country(id_country, name) VALUES('AX', 'Åland Islands');
INSERT INTO country(id_country, name) VALUES('AZ', 'Azerbaijan');
INSERT INTO country(id_country, name) VALUES('BA', 'Bosnia & Herzegovina');
INSERT INTO country(id_country, name) VALUES('BB', 'Barbados');
INSERT INTO country(id_country, name) VALUES('BD', 'Bangladesh');
INSERT INTO country(id_country, name) VALUES('BE', 'Belgium');
INSERT INTO country(id_country, name) VALUES('BF', 'Burkina Faso');
INSERT INTO country(id_country, name) VALUES('BG', 'Bulgaria');
INSERT INTO country(id_country, name) VALUES('BH', 'Bahrain');
INSERT INTO country(id_country, name) VALUES('BI', 'Burundi');
INSERT INTO country(id_country, name) VALUES('BJ', 'Benin');
INSERT INTO country(id_country, name) VALUES('BL', 'St Barthelemy');
INSERT INTO country(id_country, name) VALUES('BM', 'Bermuda');
INSERT INTO country(id_country, name) VALUES('BN', 'Brunei');
INSERT INTO country(id_country, name) VALUES('BO', 'Bolivia');
INSERT INTO country(id_country, name) VALUES('BQ', 'Caribbean NL');
INSERT INTO country(id_country, name) VALUES('BR', 'Brazil');
INSERT INTO country(id_country, name) VALUES('BS', 'Bahamas');
INSERT INTO country(id_country, name) VALUES('BT', 'Bhutan');
INSERT INTO country(id_country, name) VALUES('BV', 'Bouvet Island');
INSERT INTO country(id_country, name) VALUES('BW', 'Botswana');
INSERT INTO country(id_country, name) VALUES('BY', 'Belarus');
INSERT INTO country(id_country, name) VALUES('BZ', 'Belize');
INSERT INTO country(id_country, name) VALUES('CA', 'Canada');
INSERT INTO country(id_country, name) VALUES('CC', 'Cocos (Keeling) Islands');
INSERT INTO country(id_country, name) VALUES('CD', 'Congo (Dem. Rep.)');
INSERT INTO country(id_country, name) VALUES('CF', 'Central African Rep.');
INSERT INTO country(id_country, name) VALUES('CG', 'Congo (Rep.)');
INSERT INTO country(id_country, name) VALUES('CH', 'Switzerland');
INSERT INTO country(id_country, name) VALUES('CI', 'Côte d''Ivoire');
INSERT INTO country(id_country, name) VALUES('CK', 'Cook Islands');
INSERT INTO country(id_country, name) VALUES('CL', 'Chile');
INSERT INTO country(id_country, name) VALUES('CM', 'Cameroon');
INSERT INTO country(id_country, name) VALUES('CN', 'China');
INSERT INTO country(id_country, name) VALUES('CO', 'Colombia');
INSERT INTO country(id_country, name) VALUES('CR', 'Costa Rica');
INSERT INTO country(id_country, name) VALUES('CU', 'Cuba');
INSERT INTO country(id_country, name) VALUES('CV', 'Cape Verde');
INSERT INTO country(id_country, name) VALUES('CW', 'Curaçao');
INSERT INTO country(id_country, name) VALUES('CX', 'Christmas Island');
INSERT INTO country(id_country, name) VALUES('CY', 'Cyprus');
INSERT INTO country(id_country, name) VALUES('CZ', 'Czech Republic');
INSERT INTO country(id_country, name) VALUES('DE', 'Germany');
INSERT INTO country(id_country, name) VALUES('DJ', 'Djibouti');
INSERT INTO country(id_country, name) VALUES('DK', 'Denmark');
INSERT INTO country(id_country, name) VALUES('DM', 'Dominica');
INSERT INTO country(id_country, name) VALUES('DO', 'Dominican Republic');
INSERT INTO country(id_country, name) VALUES('DZ', 'Algeria');
INSERT INTO country(id_country, name) VALUES('EC', 'Ecuador');
INSERT INTO country(id_country, name) VALUES('EE', 'Estonia');
INSERT INTO country(id_country, name) VALUES('EG', 'Egypt');
INSERT INTO country(id_country, name) VALUES('EH', 'Western Sahara');
INSERT INTO country(id_country, name) VALUES('ER', 'Eritrea');
INSERT INTO country(id_country, name) VALUES('ES', 'Spain');
INSERT INTO country(id_country, name) VALUES('ET', 'Ethiopia');
INSERT INTO country(id_country, name) VALUES('FI', 'Finland');
INSERT INTO country(id_country, name) VALUES('FJ', 'Fiji');
INSERT INTO country(id_country, name) VALUES('FK', 'Falkland Islands');
INSERT INTO country(id_country, name) VALUES('FM', 'Micronesia');
INSERT INTO country(id_country, name) VALUES('FO', 'Faroe Islands');
INSERT INTO country(id_country, name) VALUES('FR', 'France');
INSERT INTO country(id_country, name) VALUES('GA', 'Gabon');
INSERT INTO country(id_country, name) VALUES('GB', 'Britain (UK)');
INSERT INTO country(id_country, name) VALUES('GD', 'Grenada');
INSERT INTO country(id_country, name) VALUES('GE', 'Georgia');
INSERT INTO country(id_country, name) VALUES('GF', 'French Guiana');
INSERT INTO country(id_country, name) VALUES('GG', 'Guernsey');
INSERT INTO country(id_country, name) VALUES('GH', 'Ghana');
INSERT INTO country(id_country, name) VALUES('GI', 'Gibraltar');
INSERT INTO country(id_country, name) VALUES('GL', 'Greenland');
INSERT INTO country(id_country, name) VALUES('GM', 'Gambia');
INSERT INTO country(id_country, name) VALUES('GN', 'Guinea');
INSERT INTO country(id_country, name) VALUES('GP', 'Guadeloupe');
INSERT INTO country(id_country, name) VALUES('GQ', 'Equatorial Guinea');
INSERT INTO country(id_country, name) VALUES('GR', 'Greece');
INSERT INTO country(id_country, name) VALUES('GS', 'South Georgia & the South Sandwich Islands');
INSERT INTO country(id_country, name) VALUES('GT', 'Guatemala');
INSERT INTO country(id_country, name) VALUES('GU', 'Guam');
INSERT INTO country(id_country, name) VALUES('GW', 'Guinea-Bissau');
INSERT INTO country(id_country, name) VALUES('GY', 'Guyana');
INSERT INTO country(id_country, name) VALUES('HK', 'Hong Kong');
INSERT INTO country(id_country, name) VALUES('HM', 'Heard Island & McDonald Islands');
INSERT INTO country(id_country, name) VALUES('HN', 'Honduras');
INSERT INTO country(id_country, name) VALUES('HR', 'Croatia');
INSERT INTO country(id_country, name) VALUES('HT', 'Haiti');
INSERT INTO country(id_country, name) VALUES('HU', 'Hungary');
INSERT INTO country(id_country, name) VALUES('ID', 'Indonesia');
INSERT INTO country(id_country, name) VALUES('IE', 'Ireland');
INSERT INTO country(id_country, name) VALUES('IL', 'Israel');
INSERT INTO country(id_country, name) VALUES('IM', 'Isle of Man');
INSERT INTO country(id_country, name) VALUES('IN', 'India');
INSERT INTO country(id_country, name) VALUES('IO', 'British Indian Ocean Territory');
INSERT INTO country(id_country, name) VALUES('IQ', 'Iraq');
INSERT INTO country(id_country, name) VALUES('IR', 'Iran');
INSERT INTO country(id_country, name) VALUES('IS', 'Iceland');
INSERT INTO country(id_country, name) VALUES('IT', 'Italy');
INSERT INTO country(id_country, name) VALUES('JE', 'Jersey');
INSERT INTO country(id_country, name) VALUES('JM', 'Jamaica');
INSERT INTO country(id_country, name) VALUES('JO', 'Jordan');
INSERT INTO country(id_country, name) VALUES('JP', 'Japan');
INSERT INTO country(id_country, name) VALUES('KE', 'Kenya');
INSERT INTO country(id_country, name) VALUES('KG', 'Kyrgyzstan');
INSERT INTO country(id_country, name) VALUES('KH', 'Cambodia');
INSERT INTO country(id_country, name) VALUES('KI', 'Kiribati');
INSERT INTO country(id_country, name) VALUES('KM', 'Comoros');
INSERT INTO country(id_country, name) VALUES('KN', 'St Kitts & Nevis');
INSERT INTO country(id_country, name) VALUES('KP', 'Korea (North)');
INSERT INTO country(id_country, name) VALUES('KR', 'Korea (South)');
INSERT INTO country(id_country, name) VALUES('KW', 'Kuwait');
INSERT INTO country(id_country, name) VALUES('KY', 'Cayman Islands');
INSERT INTO country(id_country, name) VALUES('KZ', 'Kazakhstan');
INSERT INTO country(id_country, name) VALUES('LA', 'Laos');
INSERT INTO country(id_country, name) VALUES('LB', 'Lebanon');
INSERT INTO country(id_country, name) VALUES('LC', 'St Lucia');
INSERT INTO country(id_country, name) VALUES('LI', 'Liechtenstein');
INSERT INTO country(id_country, name) VALUES('LK', 'Sri Lanka');
INSERT INTO country(id_country, name) VALUES('LR', 'Liberia');
INSERT INTO country(id_country, name) VALUES('LS', 'Lesotho');
INSERT INTO country(id_country, name) VALUES('LT', 'Lithuania');
INSERT INTO country(id_country, name) VALUES('LU', 'Luxembourg');
INSERT INTO country(id_country, name) VALUES('LV', 'Latvia');
INSERT INTO country(id_country, name) VALUES('LY', 'Libya');
INSERT INTO country(id_country, name) VALUES('MA', 'Morocco');
INSERT INTO country(id_country, name) VALUES('MC', 'Monaco');
INSERT INTO country(id_country, name) VALUES('MD', 'Moldova');
INSERT INTO country(id_country, name) VALUES('ME', 'Montenegro');
INSERT INTO country(id_country, name) VALUES('MF', 'St Martin (French)');
INSERT INTO country(id_country, name) VALUES('MG', 'Madagascar');
INSERT INTO country(id_country, name) VALUES('MH', 'Marshall Islands');
INSERT INTO country(id_country, name) VALUES('MK', 'North Macedonia');
INSERT INTO country(id_country, name) VALUES('ML', 'Mali');
INSERT INTO country(id_country, name) VALUES('MM', 'Myanmar (Burma)');
INSERT INTO country(id_country, name) VALUES('MN', 'Mongolia');
INSERT INTO country(id_country, name) VALUES('MO', 'Macau');
INSERT INTO country(id_country, name) VALUES('MP', 'Northern Mariana Islands');
INSERT INTO country(id_country, name) VALUES('MQ', 'Martinique');
INSERT INTO country(id_country, name) VALUES('MR', 'Mauritania');
INSERT INTO country(id_country, name) VALUES('MS', 'Montserrat');
INSERT INTO country(id_country, name) VALUES('MT', 'Malta');
INSERT INTO country(id_country, name) VALUES('MU', 'Mauritius');
INSERT INTO country(id_country, name) VALUES('MV', 'Maldives');
INSERT INTO country(id_country, name) VALUES('MW', 'Malawi');
INSERT INTO country(id_country, name) VALUES('MX', 'Mexico');
INSERT INTO country(id_country, name) VALUES('MY', 'Malaysia');
INSERT INTO country(id_country, name) VALUES('MZ', 'Mozambique');
INSERT INTO country(id_country, name) VALUES('NA', 'Namibia');
INSERT INTO country(id_country, name) VALUES('NC', 'New Caledonia');
INSERT INTO country(id_country, name) VALUES('NE', 'Niger');
INSERT INTO country(id_country, name) VALUES('NF', 'Norfolk Island');
INSERT INTO country(id_country, name) VALUES('NG', 'Nigeria');
INSERT INTO country(id_country, name) VALUES('NI', 'Nicaragua');
INSERT INTO country(id_country, name) VALUES('NL', 'Netherlands');
INSERT INTO country(id_country, name) VALUES('NO', 'Norway');
INSERT INTO country(id_country, name) VALUES('NP', 'Nepal');
INSERT INTO country(id_country, name) VALUES('NR', 'Nauru');
INSERT INTO country(id_country, name) VALUES('NU', 'Niue');
INSERT INTO country(id_country, name) VALUES('NZ', 'New Zealand');
INSERT INTO country(id_country, name) VALUES('OM', 'Oman');
INSERT INTO country(id_country, name) VALUES('PA', 'Panama');
INSERT INTO country(id_country, name) VALUES('PE', 'Peru');
INSERT INTO country(id_country, name) VALUES('PF', 'French Polynesia');
INSERT INTO country(id_country, name) VALUES('PG', 'Papua New Guinea');
INSERT INTO country(id_country, name) VALUES('PH', 'Philippines');
INSERT INTO country(id_country, name) VALUES('PK', 'Pakistan');
INSERT INTO country(id_country, name) VALUES('PL', 'Poland');
INSERT INTO country(id_country, name) VALUES('PM', 'St Pierre & Miquelon');
INSERT INTO country(id_country, name) VALUES('PN', 'Pitcairn');
INSERT INTO country(id_country, name) VALUES('PR', 'Puerto Rico');
INSERT INTO country(id_country, name) VALUES('PS', 'Palestine');
INSERT INTO country(id_country, name) VALUES('PT', 'Portugal');
INSERT INTO country(id_country, name) VALUES('PW', 'Palau');
INSERT INTO country(id_country, name) VALUES('PY', 'Paraguay');
INSERT INTO country(id_country, name) VALUES('QA', 'Qatar');
INSERT INTO country(id_country, name) VALUES('RE', 'Réunion');
INSERT INTO country(id_country, name) VALUES('RO', 'Romania');
INSERT INTO country(id_country, name) VALUES('RS', 'Serbia');
INSERT INTO country(id_country, name) VALUES('RU', 'Russia');
INSERT INTO country(id_country, name) VALUES('RW', 'Rwanda');
INSERT INTO country(id_country, name) VALUES('SA', 'Saudi Arabia');
INSERT INTO country(id_country, name) VALUES('SB', 'Solomon Islands');
INSERT INTO country(id_country, name) VALUES('SC', 'Seychelles');
INSERT INTO country(id_country, name) VALUES('SD', 'Sudan');
INSERT INTO country(id_country, name) VALUES('SE', 'Sweden');
INSERT INTO country(id_country, name) VALUES('SG', 'Singapore');
INSERT INTO country(id_country, name) VALUES('SH', 'St Helena');
INSERT INTO country(id_country, name) VALUES('SI', 'Slovenia');
INSERT INTO country(id_country, name) VALUES('SJ', 'Svalbard & Jan Mayen');
INSERT INTO country(id_country, name) VALUES('SK', 'Slovakia');
INSERT INTO country(id_country, name) VALUES('SL', 'Sierra Leone');
INSERT INTO country(id_country, name) VALUES('SM', 'San Marino');
INSERT INTO country(id_country, name) VALUES('SN', 'Senegal');
INSERT INTO country(id_country, name) VALUES('SO', 'Somalia');
INSERT INTO country(id_country, name) VALUES('SR', 'Suriname');
INSERT INTO country(id_country, name) VALUES('SS', 'South Sudan');
INSERT INTO country(id_country, name) VALUES('ST', 'Sao Tome & Principe');
INSERT INTO country(id_country, name) VALUES('SV', 'El Salvador');
INSERT INTO country(id_country, name) VALUES('SX', 'St Maarten (Dutch)');
INSERT INTO country(id_country, name) VALUES('SY', 'Syria');
INSERT INTO country(id_country, name) VALUES('SZ', 'Eswatini (Swaziland)');
INSERT INTO country(id_country, name) VALUES('TC', 'Turks & Caicos Is');
INSERT INTO country(id_country, name) VALUES('TD', 'Chad');
INSERT INTO country(id_country, name) VALUES('TF', 'French Southern Territories');
INSERT INTO country(id_country, name) VALUES('TG', 'Togo');
INSERT INTO country(id_country, name) VALUES('TH', 'Thailand');
INSERT INTO country(id_country, name) VALUES('TJ', 'Tajikistan');
INSERT INTO country(id_country, name) VALUES('TK', 'Tokelau');
INSERT INTO country(id_country, name) VALUES('TL', 'East Timor');
INSERT INTO country(id_country, name) VALUES('TM', 'Turkmenistan');
INSERT INTO country(id_country, name) VALUES('TN', 'Tunisia');
INSERT INTO country(id_country, name) VALUES('TO', 'Tonga');
INSERT INTO country(id_country, name) VALUES('TR', 'Turkey');
INSERT INTO country(id_country, name) VALUES('TT', 'Trinidad & Tobago');
INSERT INTO country(id_country, name) VALUES('TV', 'Tuvalu');
INSERT INTO country(id_country, name) VALUES('TW', 'Taiwan');
INSERT INTO country(id_country, name) VALUES('TZ', 'Tanzania');
INSERT INTO country(id_country, name) VALUES('UA', 'Ukraine');
INSERT INTO country(id_country, name) VALUES('UG', 'Uganda');
INSERT INTO country(id_country, name) VALUES('UM', 'US minor outlying islands');
INSERT INTO country(id_country, name) VALUES('US', 'United States');
INSERT INTO country(id_country, name) VALUES('UY', 'Uruguay');
INSERT INTO country(id_country, name) VALUES('UZ', 'Uzbekistan');
INSERT INTO country(id_country, name) VALUES('VA', 'Vatican City');
INSERT INTO country(id_country, name) VALUES('VC', 'St Vincent');
INSERT INTO country(id_country, name) VALUES('VE', 'Venezuela');
INSERT INTO country(id_country, name) VALUES('VG', 'Virgin Islands (UK)');
INSERT INTO country(id_country, name) VALUES('VI', 'Virgin Islands (US)');
INSERT INTO country(id_country, name) VALUES('VN', 'Vietnam');
INSERT INTO country(id_country, name) VALUES('VU', 'Vanuatu');
INSERT INTO country(id_country, name) VALUES('WF', 'Wallis & Futuna');
INSERT INTO country(id_country, name) VALUES('WS', 'Samoa (western)');
INSERT INTO country(id_country, name) VALUES('YE', 'Yemen');
INSERT INTO country(id_country, name) VALUES('YT', 'Mayotte');
INSERT INTO country(id_country, name) VALUES('ZA', 'South Africa');
INSERT INTO country(id_country, name) VALUES('ZM', 'Zambia');
INSERT INTO country(id_country, name) VALUES('ZW', 'Zimbabwe');